import opentype from 'opentype.js';
import { writeFileSync } from 'node:fs';

// Two fonts: Paytone One for Latin, Gasoek One for Korean
const latinFont = opentype.loadSync('scripts/fonts/PaytoneOne-Regular.ttf');
const koreanFont = opentype.loadSync('scripts/fonts/GasoekOne-Regular.ttf');
const FONT_SIZE = 48;

function getCharPaths(font: opentype.Font, text: string, startX: number, spacing: number) {
  const paths = [];
  let x = startX;
  for (const char of text) {
    const glyph = font.charToGlyph(char);
    const path = glyph.getPath(x, FONT_SIZE, FONT_SIZE);
    const svgPath = path.toSVG().match(/d="([^"]+)"/)?.[1] || '';
    const width = (glyph.advanceWidth || 0) * (FONT_SIZE / font.unitsPerEm);
    paths.push({ char, d: svgPath, width });
    x += width + spacing;
  }
  return { paths, totalWidth: x - spacing };
}

const hansoom = getCharPaths(latinFont, 'hansoom', 0, 2);
const hangul = getCharPaths(koreanFont, '한숨', 0, 4);

const output = `// Auto-generated by scripts/generate-watermark-paths.ts
// Fonts: Paytone One (Latin) at ${FONT_SIZE}px, Gasoek One (Korean) at ${FONT_SIZE}px
// Do not edit manually — re-run the script to regenerate

export const HANSOOM_PATHS = ${JSON.stringify(hansoom.paths, null, 2)};
export const HANGUL_PATHS = ${JSON.stringify(hangul.paths, null, 2)};
export const HANSOOM_VIEWBOX = '0 0 ${Math.ceil(hansoom.totalWidth)} ${Math.ceil(FONT_SIZE * 1.2)}';
export const HANGUL_VIEWBOX = '0 0 ${Math.ceil(hangul.totalWidth)} ${Math.ceil(FONT_SIZE * 1.2)}';
`;

writeFileSync('src/renderer/watermark-paths.ts', output);
console.log('✓ Generated watermark paths');
console.log(`  hansoom (Paytone One): ${hansoom.paths.length} chars, ${Math.ceil(hansoom.totalWidth)}px wide`);
console.log(`  한숨 (Gasoek One): ${hangul.paths.length} chars, ${Math.ceil(hangul.totalWidth)}px wide`);